# Final Exam Matrix CS


In [172]:
import numpy as np

# Fixed 3x4 matrix
matrix = np.array([
    [12, 6, 5, 6],
    [10, 2, 12, 10],
    [7, 9, 2, 2]
])

# Extract the coefficient matrix A and the right-hand-side vector b
A = matrix[:, :-1]  # First 3 columns
b = matrix[:, -1]   # Last column

# Display the full matrix, A, and b
print("Fixed 3x4 Matrix:")
print(matrix)

print("\nCoefficient Matrix A (first 3 columns):")
print(A)

print("\nRight-hand-side Vector b (last column):")
print(b)

Fixed 3x4 Matrix:
[[12  6  5  6]
 [10  2 12 10]
 [ 7  9  2  2]]

Coefficient Matrix A (first 3 columns):
[[12  6  5]
 [10  2 12]
 [ 7  9  2]]

Right-hand-side Vector b (last column):
[ 6 10  2]


# Python Code to Verify Solutions

In [174]:
# Solve using Matrix Inverse Method
try:
    A_inv = np.linalg.inv(A)  # Compute A^-1
    x_manual = np.dot(A_inv, b)  # x = A^-1 * b
    print("\nSolution using Matrix Inverse Method:")
    print(x_manual)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and cannot be inverted.")

# Solve using Gaussian Elimination
x_gaussian = np.linalg.solve(A, b)  # Direct Gaussian elimination
print("\nSolution using Gaussian Elimination (NumPy):")
print(x_gaussian)

# Verify the solution
b_check = np.dot(A, x_gaussian)  # Recompute b using A and the computed x
print("\nVerification (Ax = b):")
print(b_check)


Solution using Matrix Inverse Method:
[ 0.35123967 -0.17768595  0.57024793]

Solution using Gaussian Elimination (NumPy):
[ 0.35123967 -0.17768595  0.57024793]

Verification (Ax = b):
[ 6. 10.  2.]
